apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-builder-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cv-builder.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-builder-api
                port:
                  number: 80
