role_mapping:
  tech lead: tech_lead
  technical manager: technical_manager
  technology manager: technical_manager
  technical lead: technical_manager
  engineering manager: technical_manager
  software development senior specialist: software_development_senior_specialist
  software development analyst: software_development_analyst
  sdm: software_development_manager
  s.d.m: software_development_manager
  software development manager: software_development_manager
  business intelligence advisor: business_intelligence_advisor
  solution architect: solution_architect
  enterprise architect: solution_architect
  application architect: solution_architect
  cloud architect: solution_architect
  ai solution architect: solution_architect
  project manager: project_manager
  program manager: project_manager
  delivery project manager: project_manager
  senior team lead: senior_team_lead
  team lead: senior_team_lead
  lead engineer: senior_team_lead
  senior technical lead: senior_team_lead
  delivery head: delivery_head
  delivery manager: delivery_head
  service delivery head: delivery_head
  practice head: delivery_head
  senior hr: senior_hr
  hr manager: senior_hr
  talent acquisition lead: senior_hr
  hr business partner: senior_hr
